### ISSUE TITLE
Parametrisation without morphs

### ISSUE THREAD

**Issue by haroldgrosjean** [protocaller/ProtoCaller#10]
Hello,

I would like to use your (amazing) tool to prepare (remove alternative conformation, protonate, add missing residues, and atoms) and parameterized my protein-ligand system for simple unbiased simulations and later ABFE.

However, it does not seem possible to generate the files if morphs are not supplied. Since I am not aiming (yet) to perform relative calculations, I was wondering if it would be possible to use protocaller without supplying morphs.

Many thanks in advance,

**Comment by msuruzhon** [comment]
Hi there,

Regular topologies are a special case of morphed ones when both of your ligands are the same. So if you pass pairs of your ligands of interest in your morphs, it will write out a valid topology (two topologies in fact, but that doesn't make any difference).

This is the quickest way to do it practically. Alternatively, you can create a separate `Protein` and use its native `parametrise()` method, which will result in a `BioSimSpace` object, called `complex_template`, and then `parametrise()` another `Ligand` and load its `parametrised_files` into `BioSimSpace` as well. Then you can combine them and solvate using `solvate()` and saving that should get you what you want. That's a more roundabout way (still only a couple of lines of code), but it's still valid (and it's in fact what the method in `Ensemble` uses anyway). For more information look at https://protocaller.readthedocs.io. This method doesn't perform ligand alignment to a reference though, so the easier method is probably your best bet .

In any case, you will likely need ligand restraints if you run ABFE, which `ProtoCaller` doesn't currently support - you will have to add these using some other means.

Hope that helps.
