### ISSUE TITLE
PDBBank update and pypdb update

### ISSUE THREAD

**Issue by kexul** [protocaller/ProtoCaller#12]
Today I ran the example of  T4-lysozyme, It seems that the pypdb has been broken because the update of PDBBank. 
![图片](https://user-images.githubusercontent.com/5920217/98542169-787b8b00-22cb-11eb-9e8b-e076c1b3431b.png)

**Comment by kexul** [comment]
New readme readed, seems like you guys have found it.

**Comment by msuruzhon** [comment]
The Protein Data Bank has been rather unstable in the past half a year, and the recent update completely broke `pypdb`, and therefore `ProtoCaller`. It seems that they have made their API servers fairly stable now and they are removing all backward compatibility, so I modified a chunk of the code to accommodate that. I have pushed the commit now and the updated build should be available from `conda` within 1 hour. All the tests now pass, as well as the T4-lysozyme example.
