### ISSUE TITLE
BioSimSpace  module cannot be imoprted in 1.1.2

### ISSUE THREAD

**Issue by kexul** [protocaller/ProtoCaller#13]
Since pypdb was broken, I switch to 1.1.2 as the README suggested. But I cannot import protocaller any more. The error shows that `ImportError: BioSimSpace module cannot be imported`

**Comment by msuruzhon** [comment]
This is very likely a `conda` problem, so I would advice you to install ProtoCaller in its own empty environment created with `python=3.7`. I have also noticed that the resolution times can be incredibly slow, so you might benefit from installing it using [`mamba`](https://github.com/mamba-org/mamba) instead.

**Comment by kexul** [comment]
I did install protocaller in a clean new environment with python3.7.

**Comment by kexul** [comment]
I switch to the default installation method use `conda install -c conda-forge -c omnia -c michellab -c essexlab protocaller` since you said you've updated the conda package. Now everything works. Thanks for your quick reply and fix.
