### ISSUE TITLE
Performing Free Energy Calculations failed

### ISSUE THREAD

**Issue by kexul** [protocaller/ProtoCaller#14]
It seems like there were some bugs in `ProtoCaller/Utils/fileio.py` , when I run the 'Performing Free Energy Calculation' example, the error raised. 
```
Traceback (most recent call last):
  File "run.py", line 41, in <module>
    with workdir:
  File "/root/anaconda3/envs/uii/lib/python3.7/site-packages/ProtoCaller/Utils/fileio.py", line 69, in __enter__
    _os.makedirs(self.dirname)
  File "/root/anaconda3/envs/uii/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```
I ran the code by : `python run.py --mode bound --workdir /root/proto/kinase/2OJ9/mola~molb/` , the `kinase` directory were generated by protocaller, and there were complex_final.gro and complex_final.top files in the mola~molb directory.

**Comment by msuruzhon** [comment]
This seems to be just some weird behaviour by `os.makedirs` when there is a trailing slash. If you remove the final slash, it should work.

**Comment by msuruzhon** [comment]
I have now pushed a small update that should take care of this behaviour.
