### ISSUE TITLE
Can I use ProtoCaller in protein-protein system?

### ISSUE THREAD

**Issue by meetxinzhang** [protocaller/ProtoCaller#24]

**Comment by msuruzhon** [comment]
Hi,

ProtoCaller can only deal with ligand-ligand perturbations. If we are talking about a protein-protein system and you are interested in a ligand perturbation in one of them, then this should be possible with some tweaking - simply create two separate `Ensemble` systems and after you perform parametrisation and alignment on both of them, you can combine the resulting `BioSimSpace` objects, and even manipulate them further within `BioSimSpace` if you need to.

**Comment by kexul** [comment]
If you are talking about protein-protein mutation, here is a nice tutorial using biobb.  https://biobb-wf-pmx-tutorial.readthedocs.io/en/latest/tutorial.html @MeetDevin .

**Comment by meetxinzhang** [comment]
> If you are talking about protein-protein mutation, here is a nice tutorial using biobb. https://biobb-wf-pmx-tutorial.readthedocs.io/en/latest/tutorial.html @MeetDevin .

thanks, biobb is particularly useful for my work.

**Comment by meetxinzhang** [comment]
> If you are talking about protein-protein mutation, here is a nice tutorial using biobb. https://biobb-wf-pmx-tutorial.readthedocs.io/en/latest/tutorial.html @MeetDevin .

thanks, biobb is particularly useful for my work

> Hi,
> 
> ProtoCaller can only deal with ligand-ligand perturbations. If we are talking about a protein-protein system and you are interested in a ligand perturbation in one of them, then this should be possible with some tweaking - simply create two separate `Ensemble` systems and after you perform parametrisation and alignment on both of them, you can combine the resulting `BioSimSpace` objects, and even manipulate them further within `BioSimSpace` if you need to.

thanks, I will try.
