### ISSUE TITLE
An input file contains a line longer than 4095 characters

### ISSUE THREAD

**Issue by kexul** [protocaller/ProtoCaller#26]
Hi, my PDBId is `6h3k`, I used protocaller to prepare my system. In minimization, `gmx grompp`  raised an error: 
`Fatal error:
An input file contains a line longer than 4095 characters, while the buffer
passed to fgets2 has size 4095. The line starts with: '   4134   4135      '`

Here is my `complex_final.top` generated by protocaller, in line `9461`, there are many `@` characters. 

[complex_final.zip](https://github.com/protocaller/ProtoCaller/files/6021919/complex_final.zip)

**Comment by kexul** [comment]
But the `complex.top ` is fine in the line contain `4134 4135`. 
![image](https://user-images.githubusercontent.com/5920217/108709591-e16ed200-754d-11eb-973b-c67a9f6cb9f2.png)

[complex.zip](https://github.com/protocaller/ProtoCaller/files/6021945/complex.zip)

**Comment by msuruzhon** [comment]
Is this error reproducible? I have had similar looking errors in a completely different setting (not related to ProtoCaller) when there is a problem with file I/O, and that results in these null characters `^@` being written out for some reason. Also, does the file work if you manually remove the null characters in `vim`?

**Comment by kexul** [comment]
It's not always reproducible, this is the first time I encountered it. I have not encountered it before, even with the same protein. 
That's a good idea, I'll  try remove it manually.

**Comment by kexul** [comment]
It worked, thanks.
