### ISSUE TITLE
Can I supply a ligand coordinate file as input?

### ISSUE THREAD

**Issue by xiki-tempula** [protocaller/ProtoCaller#28]
Sorry, I'm new to ProtoCaller. I wodner if it is possible to feed pdb instead of smiles string as ligand input?
Like `ProtoCaller.Ensemble.Ligand.Ligand('lig.pdb')`

**Comment by tsenapathi** [comment]
Hi @xiki-tempula you can use the coordinates of ligands as an SDF file. See the Sialyltransferase example `https://github.com/protocaller/ProtoCaller/blob/master/examples/Sialyltransferase_2.py `
