### ISSUE TITLE
Molecule ID not found

### ISSUE THREAD

**Issue by kexul** [protocaller/ProtoCaller#34]
Hi, I used the following code: 
```
protein = Protein('4NA9', ligand_ref='301')
```
which raised an error:
```
ValueError: Molecule ID not found: 301
```
I've confirmed that molecule 301 is in the pdb file.

**Comment by msuruzhon** [comment]
Hi, since your protein has two chains, the residue ID is potentially ambiguous, so you need to add the chain name in front as well, so e.g.:

`protein = Protein('4NA9', ligand_ref='H301')`

**Comment by msuruzhon** [comment]
Hi, since your protein has two chains, the residue ID is potentially ambiguous, so you need to add the chain name in front as well, so e.g.:

```
protein = Protein('4NA9', ligand_ref='H301')
```
